os: linux
dist: xenial
language: python

git:
  depth: false  # "Shallow clone detected during the analysis"

jobs:
  include:
    - stage: "Code analyze"
      python: 3.8
      addons:
        sonarcloud:
          organization: "brobots-corporation"
      script: sonar-scanner
    - stage: "deploy pypi"
      script: skip
      deploy:
        provider: pypi
        username: "__token__"
        password: $PYPI_TOKEN
        distributions: "sdist bdist_wheel"
        on:
          tags: true
notifications:
  email:
    on_failure: change